# HLint configuration file
# https://github.com/ndmitchell/hlint

# Ignore some builtin hints
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Move brackets to avoid $"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Replace case with maybe"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Use const"}
- ignore: {name: "Use if"}
- ignore: {name: "Use maybe"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Use notElem"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use camelCase" }
- ignore: {name: "Use fmap" }
- ignore: {name: "Redundant $!" }
- ignore: {name: "Reduce duplication" }
- ignore: {name: "Use section" }
