#!/bin/bash

function usage()
{
    echo "USAGE: $0 [--check]"
    exit 1
}

if [ "$1" == "--help" ]; then
    usage
fi

if [ "$1" == "--check" ]; then
    mode=check
elif [ -z "$1" ]; then
    mode=inplace
else
    usage
fi

fourmolu --mode $mode --indentation 2 --function-arrows leading --comma-style leading --import-export-style diff-friendly \
  --indent-wheres false --let-style auto --in-style right-align \
  $(find src test -name '*.hs')
